---
-   name: Install packages
    apt:
        name: "{{ packages }}"
        state: present

-   name: Check if certificate already exists.
    stat:
        path: /etc/letsencrypt/live/{{ domain_name }}/cert.pem
    register: letsencrypt_cert

-   name: debug msg to show if cert exist
    debug: msg="{{ letsencrypt_cert.stat.exists }}"

-   name: Stop nginx to allow standalone certbot certificate management
    service:
      name: nginx
      state: stopped

-   name: Generate new certificate if one doesn't exist.
    when: not letsencrypt_cert.stat.exists
    command:
      cmd: "certbot certonly --standalone --noninteractive --expand --agree-tos --email {{ admin_email }} -d {{ domain_name }} -d www.{{ domain_name }}"

-   name: Renew existing certificate if needed.
    when: letsencrypt_cert.stat.exists
    command:
      cmd: "certbot renew --standalone --noninteractive"
    register: certbot_renew
    changed_when: >-
      'no renewals were attempted' not in (certbot_renew.stdout | lower)
      and 'not yet due for renewal' not in (certbot_renew.stdout | lower)

-   name: Remove default conf
    file:
        state: absent
        path: /etc/nginx/sites-enabled/default

-   name: Template nginx config to server
    copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        mode: "644"
    notify:
    - Restart nginx


-   name: Template nginx site config to server
    template:
        src: load-balancer.conf.j2
        dest: /etc/nginx/sites-available/load-balancer.conf
        mode: "644"
    notify:
    - Restart nginx

-   name: Link site to enabled
    file:
        state: link
        force: yes
        src: /etc/nginx/sites-available/load-balancer.conf
        path: /etc/nginx/sites-enabled/load-balancer.conf
    notify:
    - Restart nginx

-   name: Start services after certificate management.
    service:
      name: nginx
      state: started

- name: Ensure nginx is running with latest config (always)
  service:
    name: nginx
    state: restarted
    enabled: yes
